### ISSUE TITLE
Mastodon support

### ISSUE THREAD

**Issue by dagobertdebug** [thalesgroup-cert/Watcher#88]
Hi

RSS-Bridge should be capable for monitoring Mastodon. Could you please help with providing the correct format of the link to add.

Like for Twitter it is: 

hxxp://xx.xx.xx.xx/?action=display&bridge=Twitter&context=By+username&u=xxxxxx&norep=on&nopic=on&noimg=on&noimgscaling=on&format=Mrss

Is this the correct format for Mastodon:

hxxp://xx.xx.xx.xx/?action=display&bridge=MastodonBridge&canusername=xxxxxx&norep=on&noboost=on&signaturetype=noquery&format=Mrss

Many thanks for your help and this great tool!

**Comment by Felix83000** [comment]
Hi,

Please read the doc here: https://thalesgroup-cert.github.io/Watcher/README.html#how-to-use-rss-bridge-to-add-more-sources-from-facebook-googlesearch-youtube

Thanks!

**Comment by dagobertdebug** [comment]
Hi, thanks, the information from Mastodon shows up in the "Articles" pane.... but they are not shown in a compact way like "tweets"... any idea/plans to support a similar visualisation of Mastodon "tweets" like they are already shown for Twitter?
![image](https://user-images.githubusercontent.com/30775398/208950567-2ba71f81-ce5c-4a72-bd8a-24fb96f08b1c.png)

**Comment by Felix83000** [comment]
Hi,

We are currently using **react-twitter-widgets** ReactJS module.

We could modified this [React.Component](https://github.com/thalesgroup-cert/Watcher/blob/master/Watcher/Watcher/frontend/src/components/ThreatsWatcher/TwitterTweet.js) in order to show Mastodon 'tweets' with the Twitter tweets but there is no plan to do it on our side for now. 

We do not know if a Mastodon ReactJS module exist. If not, it can be done from scratch.

Please post a pull request if you want to develop this feature.

Best regards
